-- Tests for surround keymaps (HAEI/Graphite layout)
-- Add ys / delete ds / change cs. Visual: native v/V to select, then s to
-- trigger. In this layout i->l and r->i (operator-pending), so the inner-word
-- motion is `rw` (not `iw`): the add-surround form is `ysrw(`.
-- Run via: make test

local function set_curpos(pos)
  vim.api.nvim_win_set_cursor(0, { pos[1], pos[2] - 1 })
end

local function set_lines(lines)
  vim.api.nvim_buf_set_lines(0, 0, -1, false, lines)
end

local function check_lines(lines)
  assert.are.same(lines, vim.api.nvim_buf_get_lines(0, 0, -1, false))
end

-- Add nvim-surround to runtimepath (needed for headless plenary tests)
local surround_path = vim.fn.stdpath("data") .. "/lazy/nvim-surround"
if vim.fn.isdirectory(surround_path) == 1 then
  vim.opt.runtimepath:append(surround_path)
end

-- nvim-surround v4: keymaps are auto-bound by the plugin's plugin/ dir on
-- runtimepath (no `keymaps` field in setup). Disable the default visual `S`
-- and bind `s` ourselves, matching config/keymaps/surround.fnl.
vim.g.nvim_surround_no_visual_mappings = true
vim.cmd("runtime! plugin/nvim-surround.lua")
vim.keymap.set("x", "s", "<Plug>(nvim-surround-visual)", { desc = "Surround visual selection" })
vim.keymap.set("x", "gS", "<Plug>(nvim-surround-visual-line)", { desc = "Surround visual selection (newlines)" })

-- Load the REAL config opts so the test can't drift from lua/plugins/surround.lua.
local spec = require("plugins.surround")
require("nvim-surround").setup(spec.opts)

-- Minimal HAEI operator-pending layer that surround motions rely on:
-- i->l (right), r->i (inner), t->a (around). Mirrors lua/config/keymaps.lua.
vim.keymap.set({ "n", "o", "x" }, "i", "l")
vim.keymap.set({ "o", "x" }, "r", "i")
vim.keymap.set({ "o", "x" }, "t", "a")

describe("surround", function()
  before_each(function()
    local bufnr = vim.api.nvim_create_buf(true, true)
    vim.api.nvim_win_set_buf(0, bufnr)
    vim.bo[bufnr].modifiable = true
  end)

  describe("add surround (ys)", function()
    it("surrounds word with parentheses using ys", function()
      set_lines({ "hello world" })
      set_curpos({ 1, 1 })
      vim.cmd("normal ysrw(")
      check_lines({ "(hello) world" })
    end)

    it("surrounds word with spaced parentheses using )", function()
      set_lines({ "hello world" })
      set_curpos({ 1, 1 })
      vim.cmd("normal ysrw)")
      check_lines({ "( hello ) world" })
    end)

    it("surrounds word with brackets using [", function()
      set_lines({ "hello world" })
      set_curpos({ 1, 1 })
      vim.cmd("normal ysrw[")
      check_lines({ "[hello] world" })
    end)

    it("surrounds word with spaced brackets using ]", function()
      set_lines({ "hello world" })
      set_curpos({ 1, 1 })
      vim.cmd("normal ysrw]")
      check_lines({ "[ hello ] world" })
    end)

    it("surrounds word with braces using {", function()
      set_lines({ "hello world" })
      set_curpos({ 1, 1 })
      vim.cmd("normal ysrw{")
      check_lines({ "{hello} world" })
    end)

    it("surrounds word with spaced braces using }", function()
      set_lines({ "hello world" })
      set_curpos({ 1, 1 })
      vim.cmd("normal ysrw}")
      check_lines({ "{ hello } world" })
    end)

    it("surrounds word with double quotes", function()
      set_lines({ "hello world" })
      set_curpos({ 1, 1 })
      vim.cmd('normal ysrw"')
      check_lines({ '"hello" world' })
    end)

    it("surrounds word with single quotes", function()
      set_lines({ "hello world" })
      set_curpos({ 1, 1 })
      vim.cmd("normal ysrw'")
      check_lines({ "'hello' world" })
    end)
  end)

  describe("alias b (any bracket, tight add)", function()
    it("ysrwb adds tight parentheses", function()
      set_lines({ "hello world" })
      set_curpos({ 1, 1 })
      vim.cmd("normal ysrwb")
      check_lines({ "(hello) world" })
    end)

    it("dsb deletes any bracket", function()
      set_lines({ "{hello} world" })
      set_curpos({ 1, 2 })
      vim.cmd("normal dsb")
      check_lines({ "hello world" })
    end)
  end)

  describe("bracket spacing (opening tight, closing spaced)", function()
    it("ysrw( is tight", function()
      set_lines({ "hello world" })
      set_curpos({ 1, 1 })
      vim.cmd("normal ysrw(")
      check_lines({ "(hello) world" })
    end)

    it("ysrw) is spaced", function()
      set_lines({ "hello world" })
      set_curpos({ 1, 1 })
      vim.cmd("normal ysrw)")
      check_lines({ "( hello ) world" })
    end)

    it("ysrw< is tight", function()
      set_lines({ "hello world" })
      set_curpos({ 1, 1 })
      vim.cmd("normal ysrw<")
      check_lines({ "<hello> world" })
    end)
  end)

  describe("surround line (yss)", function()
    it("surrounds entire line with parentheses", function()
      set_lines({ "hello world" })
      set_curpos({ 1, 1 })
      vim.cmd("normal yss(")
      check_lines({ "(hello world)" })
    end)

    it("surrounds entire line with quotes", function()
      set_lines({ "hello world" })
      set_curpos({ 1, 1 })
      vim.cmd('normal yss"')
      check_lines({ '"hello world"' })
    end)
  end)

  describe("delete surround (ds)", function()
    it("deletes parentheses", function()
      set_lines({ "(hello) world" })
      set_curpos({ 1, 2 })
      vim.cmd("normal ds(")
      check_lines({ "hello world" })
    end)

    it("deletes brackets", function()
      set_lines({ "[hello] world" })
      set_curpos({ 1, 2 })
      vim.cmd("normal ds[")
      check_lines({ "hello world" })
    end)

    it("deletes braces", function()
      set_lines({ "{hello} world" })
      set_curpos({ 1, 2 })
      vim.cmd("normal ds{")
      check_lines({ "hello world" })
    end)

    it("deletes double quotes", function()
      set_lines({ '"hello" world' })
      set_curpos({ 1, 2 })
      vim.cmd('normal ds"')
      check_lines({ "hello world" })
    end)

    it("deletes single quotes", function()
      set_lines({ "'hello' world" })
      set_curpos({ 1, 2 })
      vim.cmd("normal ds'")
      check_lines({ "hello world" })
    end)
  end)

  describe("change surround (cs)", function()
    it("changes parentheses to brackets", function()
      set_lines({ "(hello) world" })
      set_curpos({ 1, 2 })
      vim.cmd("normal cs([")
      check_lines({ "[hello] world" })
    end)

    it("changes brackets to braces", function()
      set_lines({ "[hello] world" })
      set_curpos({ 1, 2 })
      vim.cmd("normal cs[{")
      check_lines({ "{hello} world" })
    end)

    it("changes double quotes to single quotes", function()
      set_lines({ '"hello" world' })
      set_curpos({ 1, 2 })
      vim.cmd("normal cs\"'")
      check_lines({ "'hello' world" })
    end)
  end)

  describe("visual surround (v to select, s to surround)", function()
    it("vrws( surrounds visual selection with parentheses", function()
      set_lines({ "hello world" })
      set_curpos({ 1, 1 })
      vim.cmd("normal vrws(")
      check_lines({ "(hello) world" })
    end)

    it('vrws" surrounds visual selection with quotes', function()
      set_lines({ "hello world" })
      set_curpos({ 1, 1 })
      vim.cmd('normal vrws"')
      check_lines({ '"hello" world' })
    end)

    it("VgS( surrounds visual line selection with newlines", function()
      set_lines({ "hello world" })
      set_curpos({ 1, 1 })
      vim.cmd("normal VgS(")
      check_lines({ "(", "hello world", ")" })
    end)
  end)

  describe("markdown surrounds", function()
    it("surrounds with bold (**)", function()
      set_lines({ "hello world" })
      set_curpos({ 1, 1 })
      vim.cmd("normal ysrw*")
      check_lines({ "**hello** world" })
    end)

    it("surrounds with italic (_)", function()
      set_lines({ "hello world" })
      set_curpos({ 1, 1 })
      vim.cmd("normal ysrw_")
      check_lines({ "_hello_ world" })
    end)

    it("surrounds with strikethrough (~)", function()
      set_lines({ "hello world" })
      set_curpos({ 1, 1 })
      vim.cmd("normal ysrw~")
      check_lines({ "~hello~ world" })
    end)

    it("deletes bold markers (requires 2x ds*)", function()
      set_lines({ "**hello** world" })
      set_curpos({ 1, 3 })
      vim.cmd("normal ds*ds*")
      check_lines({ "hello world" })
    end)

    it("deletes italic markers", function()
      set_lines({ "_hello_ world" })
      set_curpos({ 1, 2 })
      vim.cmd("normal ds_")
      check_lines({ "hello world" })
    end)
  end)

  describe("delete surrounding tag (dst)", function()
    it("deletes surrounding HTML tag", function()
      set_lines({ "<div>hello</div>" })
      set_curpos({ 1, 6 })
      vim.cmd("normal dst")
      check_lines({ "hello" })
    end)

    it("deletes nested tag from inside", function()
      set_lines({ "<div><span>hello</span></div>" })
      set_curpos({ 1, 12 })
      vim.cmd("normal dst")
      check_lines({ "<div>hello</div>" })
    end)
  end)

  describe("change backtick to single quote (cs`')", function()
    it("changes backtick to single quote", function()
      set_lines({ "`hello` world" })
      set_curpos({ 1, 2 })
      vim.cmd("normal cs`'")
      check_lines({ "'hello' world" })
    end)
  end)

  describe("treesitter surrounds", function()
    pending("ysitf surrounds with function outer (requires TS parser)")
    pending("ysitt surrounds with tag outer (requires TS parser)")
    pending("ysitc surrounds with class outer (requires TS parser)")
  end)
end)
