-- [nfnl] fnl/config/keymaps/modes.fnl
require("config.keymaps.utils")
require("config.keymaps.insert")
require("config.keymaps.terminal")
require("config.keymaps.movement")
require("config.keymaps.natives")
require("config.keymaps.config")
require("config.keymaps.edit")
require("config.keymaps.search")
require("config.keymaps.surround")
return require("config.keymaps.utils")
