-- [nfnl] fnl/config/keymaps/modes.fnl
require("config.keymaps.utils")
require("config.keymaps.insert")
require("config.keymaps.terminal")
require("config.keymaps.movement")
require("config.keymaps.markdown")
require("config.keymaps.pickers")
require("config.keymaps.natives")
require("config.keymaps.search")
return require("config.keymaps.utils")
