-- register a command "KeymapUtilsPrint"
-- copy/reuse logic from
--/home/yuv/.config/nvim/scripts/export-keymaps.lua

-- usage: $ KeymapUtilsPrint
-- opens a new buffer with the output
--
--
--add new option [disabled] that accepts boolean
-- with the requirement
--  Given any nested table includes [disabled] = true
--  Then It should not be mapped in nvim
--  And should be printed using "KeymapUtilsPrint" with a '*' prepending it
