return {
	-- Simple boolean/value toggler
	{
		"rmagatti/alternate-toggler",
		event = { "BufReadPost" },
		config = function()
			require("alternate-toggler").setup({
				alternates = {
					["true"] = "false",
					["True"] = "False",
					["TRUE"] = "FALSE",
					["yes"] = "no",
					["Yes"] = "No",
					["YES"] = "NO",
					["1"] = "0",
					["on"] = "off",
					["On"] = "Off",
					["ON"] = "OFF",
					["enable"] = "disable",
					["Enable"] = "Disable",
					["ENABLE"] = "DISABLE",
					["enabled"] = "disabled",
					["Enabled"] = "Disabled",
					["ENABLED"] = "DISABLED",
					["&&"] = "||",
					["and"] = "or",
					["And"] = "Or",
					["AND"] = "OR",
					["left"] = "right",
					["Left"] = "Right",
					["LEFT"] = "RIGHT",
					["up"] = "down",
					["Up"] = "Down",
					["UP"] = "DOWN",
					["public"] = "private",
					["Public"] = "Private",
					["PUBLIC"] = "PRIVATE",
					["const"] = "let",
					["width"] = "height",
					["Width"] = "Height",
					["WIDTH"] = "HEIGHT",
					["horizontal"] = "vertical",
					["Horizontal"] = "Vertical",
					["HORIZONTAL"] = "VERTICAL",
				},
			})
		end,
		keys = {
			{ "<C-t>", "<cmd>ToggleAlternate<cr>", desc = "Toggle alternate" },
		},
	},
}
